apiVersion: deckhouse.io/v1alpha2
kind: StaticInstance
metadata:
  name: tdh-worker-01
  labels:
    role: worker
spec:
  address: "192.168.142.95"
  credentialsRef:
    kind: SSHCredentials
    name: caps
