apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: system
spec:
  nodeTemplate:
    labels:
      node-role.deckhouse.io/system: ""
    taints:
      - effect: NoExecute
        key: dedicated.deckhouse.io
        value: system
  # Пример для узлов типа Static.
  nodeType: Static
  staticInstances:
    count: 1
    labelSelector:
      matchLabels:
        role: system
