apiVersion: deckhouse.io/v1alpha2
kind: StaticInstance
metadata:
  name: tdh-front-01
  labels:
    role: front
spec:
  address: "192.168.142.93"
  credentialsRef:
    kind: SSHCredentials
    name: caps
