apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: main
spec:
  ingressClass: nginx
  inlet: HostWithFailover
  nodeSelector:
    node-role.deckhouse.io/frontlb: ""
  tolerations:
  - effect: NoExecute
    key: dedicated.deckhouse.io
    value: frontlb
