apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-external
provisioner: nfs.csi.k8s.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
parameters:
  server: "192.168.142.99"
  share: "/mnt/nfs-storage/exports"
