apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mon-repl-pvc
  namespace: d8-monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-external
  resources:
    requests:
      storage: 100Gi
