apiVersion: v1
kind: Secret
metadata:
  name: csi-nfs-tls
  namespace: kube-system
type: Opaque
stringData:
  ca.crt: |
    REPLACE_WITH_CA_PEM
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: csi-nfs
spec:
  enabled: true
  version: 1
  settings:
    tlsParameters:
      ca: "REPLACE_WITH_BASE64_CA_PEM"
