apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-external-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-external
  resources:
    requests:
      storage: 10Gi
